name: Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: 05-raylib
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build -Doptimize=ReleaseFast
      - uses: actions/upload-artifact@v4
        with:
          name: myapp-macos
          path: 05-raylib/zig-out/bin/

  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 05-raylib
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - run: sudo apt-get install -y libraylib-dev libgl-dev libx11-dev
      - run: zig build -Doptimize=ReleaseFast
      - uses: actions/upload-artifact@v4
        with:
          name: myapp-linux
          path: 05-raylib/zig-out/bin/
